project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ryuki Matsuura"

  page-footer:
<<<<<<< HEAD
    left: "&copy; Copyright 2022, Ryuki Matsuura"
=======
    left: "&copy; Copyright 2025, Ryuki Matsuura"
>>>>>>> gh-pages-7
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: publication.qmd
        text: Publication

<<<<<<< HEAD
=======
      - href: fluency_annotation_sys.qmd
        text: Fluency Annotation System

>>>>>>> gh-pages-7
      #- href: projects/index.qmd
      #  text: Projects

      # - href: about.qmd
      #   text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



