---
title: "Publication"
---

## **Articles in Refereed Journals**

-   Arai, Y., **Matsuura, R.**, Eguchi, M., & Suzuki, S. (2026) Tracking the Longitudinal Change of Flow Experience in an EFL Conversation Course. *The Journal for the Psychology of Language Learning*. <https://www.jpll.org/index.php/journal/article/view/253>

-   Takatsu, H., Suzuki, S**.**, Eguchi, M., **Matsuura, R.**, Saeki, M., & Matsuyama, Y. (2026). Gnowsis: Multimodal multitask learning for oral proficiency assessments. *Computer Speech & Language*. [https://www.sciencedirect.com/science/article/pii/S0885230825000853](https://www.sciencedirect.com/science/article/pii/S0885230825000853?via%3Dihub)

-   Suzuki, S., Takatsu, H., **Matsuura, R.**, Koyama, M., Saeki, M., & Matsuyama, Y. (2025). Feedforwarding Diagnostic Language Assessment: AI-Driven Weakness Identification and Contextualised Feedback for L2 Speaking. *Language Testing*. <https://doi.org/10.1177/02655322251348725>

-   **Matsuura, R.**, Suzuki, S., Takizawa, K., Saeki, M., & Matsuyama, Y. (2025). Gauging the Validity of Machine Learning-Based Temporal Feature Annotation to Measure Fluency in Speech Automatically. *Research Methods in Applied Linguistics*, *4*(1), 1-23. <https://doi.org/10.1016/j.rmal.2024.100177>

## **Articles in Refereed Conference Proceedings**

-   **Matsuura, R.**, Bharadwaj, S., Liu, J., & Govindarajan, D. K. (2025). EmoNews: A Spoken Dialogue System for Expressive News Conversations. *Proc. of SigDIAL 2025.* <https://arxiv.org/abs/2506.13894>

-   Saeki, M., Takatsu, H., Kurata, F., Suzuki, S., Eguchi, M., **Matsuura, R.**, Takizawa, K., Yoshikawa, S., & Matsuyama, Y. (2024). InteLLA: Intelligent Language Learning Assistant for Assessing Language Proficiency Through Interviews and Roleplays. *Proceedings of SIGDIAL 2024*, 385-399. <https://aclanthology.org/2024.sigdial-1.34/>

-   **Matsuura, R.** & Suzuki, S. (2023). Prompt-independent Automated Scoring of L2 Oral Fluency by Capturing Prompt Effects. *Proc. of Artificial Intelligence in Education (AIED)*. <https://doi.org/10.1007/978-3-031-36272-9_62>

-   **Matsuura, R.**, Suzuki, S., Saeki, M., Ogawa, T., & Matsuyama, Y. (2022). Refinement of Utterance Fluency Feature Extraction and Automated Scoring of L2 Oral Fluency with Dialogic Features. *Proc. of Asia-Pacific Signal and Information Processing Association Annual Summit and Conference (APSIPA ASC)*, 1312-1320. <https://doi.org/10.23919/APSIPAASC55919.2022.9980148>

## Articles in Non-Refereed Journals and Conference Proceedings

-   Matsuyama, Y., Saeki, M., Takatsu, H., **Matsuura, R.**, Kurata, F., & Suzuki, S. (2023). InteLLA: Dialog-based English speaking assessment agent that elicits learner’s language ability. Journal of ASJ. 79(3), 162-169. (松山洋一，佐伯真於，高津弘明，松浦瑠希，倉田楓真，鈴木駿吾．(2023)．学習者の能力を引き出す言語運用能力判定エージェント InteLLA の開発と運用．日本音響学会誌．79(3), 162-169.)

-   **Matsuura, R.**, Suzuki, S., Saeki, M., Fujie, S., Ogawa, T., & Matsuyama, Y. (2022). Automated Scoring of L2 Oral Fluency Using Dialogic Features. Proc. of Sound Symposium. 2022-SLP-142(47), 1-6. (松浦瑠希，鈴木駿吾，佐伯真於，藤江真也，小川哲司，松山洋一．(2022)．対話特徴を用いた第二言語発話の流暢性自動採点. 音学シンポジウム. 2022-SLP-142(47), 1-6.)

-   **Matsuura, R.**, Suzuki, S., Saeki, M., Ogawa, T., & Matsuyama, Y. (2022). Automated scoring of L2 fluency based on detection of disfluency words and pause locations. Proc. of the Acoustical Society of Japan (ASJ). 1351-1354. (松浦瑠希，鈴木駿吾，佐伯真於，小川哲司，松山洋一．(2022)．言い淀みとポーズ位置検出に基づく第二言語発話の流暢性自動採点．日本音響学会研究発表会講演論文集．pp.1351-1354.)

-   Saeki, M., **Matsuura, R.**, Suzuki, S., Miyagi, K., Kobayashi, T., Matsuyama, Y. (2021). InteLLA: A Speaking Proficiency Assessment Conversational Agent with Adaptive Interview Strategy. Papers of the special interest group on Spoken Language Understanding and Dialogue processing (SIG-SLUD). 93, 15-20. (佐伯真於，松浦瑠希，鈴木駿吾，宮城琴佳，小林哲則，松山洋一．(2021)．InteLLA：適応的な質問戦略を有するスピーキング能力判定会話エージェント．人工知能学会研究会資料 言語・音声理解と対話処理研究会. 93巻, 15-20.) (**The Japanese Society of Artificial Intelligence Incentive Award**)

## Presentation

### Invited Talks

-   **Matsuura, R**. (2025, May). The Development and Evaluation of an Automatic Fluency Annotation System. 8th Language Learning Assessment Group Meeting, University of Tsukuba. (松浦瑠希，(2025, 5月)．流暢性自動アノテーションシステムの開発と評価．第8回言語学習評価研究会，筑波大学．

-   **Matsuura, R**. (2025, May). The Utilization of an Automatic Fluency Annotation System (Workshop). 8th Language Learning Assessment Group Meeting, University of Tsukuba. (松浦瑠希，(2025, 5月)．流暢性自動アノテーションシステムの活用（ワークショップ）．第8回言語学習評価研究会，筑波大学．

-   Suzuki, S., Saeki, M., & **Matsuura, R.** (2023, June). Pedagogical potential of multimodal conversational AI for foreign language learning and assessment. Paper presented at Korean PhD students and researchers in the UK (KRUK) (Zoom).

-   Suzuki, S., Saeki, M., & **Matsuura, R.** (2022, July). Development of Online Language Learning Assistant AI System that Grows with Humans. International Collaborative Practice S V: Computer-Assisted Language Learning, University of Tokyo.

-   Suzuki, S. & **Matsuura, R.** (2022, February). L2 oral fluency: From the construct definition to automated scoring. Applied Linguistics Research Circle Weekly Talk, University of Reading (Zoom).

### Refereed Paper and Poster Presentations

-   **Matsuura, R.**, & van Compernolle, Rémi A. (2025, March) Pragmatic Instruction Beyond English: A Qualitative Synthesis of Instructional Effects in L2 Japanese Pragmatics. AAAL. Chicago, US.

<!-- -->

-   Konishi , T., Mukai, Y., Suzuki, S., Hitomi, K., **Matsuura, R.**, & Kanzawa, K. (2025, Sep.) Investigating Effects of Speech Fluency and Rhythm in English on Japanese Learners' Task Delivery Scores. SLRF. Flagstaff, US.

-   Murao, R., **Matsuura, R.**, Webb, S., & Boers, F. (2025, June). Exploring Frequency Effects on EFL Learners' Syntactic Knowledge of High-Frequency Verbs. EuroSLA. Tromsø, Norway.

-   Murao, R., **Matsuura, R.**, Webb, S., & Boers, F. (2025, June). Mastering High-Frequency Verbs: Effects of Frequency and Proficiency on the Acquisition of Verb Subcategorization Frames. Vocab\@Marryland, Marryland, US.

-   **Matsuura, R.** (2025, March). Uncovering the Power of Dialogic Task Repetition: Focusing on L2 Fluency Development. AAAL. Denver, US.

-   Custance, I. & **Matsuura, R.** (2025, March). The Longitudinal Impact of Reflective Post-Tasks on Fluency Development in Monologic Impromptu Speeches. AAAL. Denver, US.

-   Koyama, M., Suzuki, S., & **Matsuura, R.** (2025, March). Exploring Cognitive Processes Underlying Pauses and Disfluency Phenomena: A Mixed-Methods Study. AAAL. Denver, US.

-   **Matsuura, R.**, Suzuki, S., Eguchi, M., Saeki, M., & Matsuyama, Y. (2024, August). Which Lexical Errors Trigger Recasts? Differential Effects of the Rhetorical Role on Dialogic Comprehensibility. AILA. Kuala Lumpur, Malaysia.

-   Suzuki, S., Takatsu, H., **Matsuura, R.**, Saeki, M., Arai, Y., & Matsuyama, Y. (2024, July). You may say this better: Consequential validity evidence for diagnostic speaking assessment on lexical use. LTRC. Innsbruck, Austria.

-   Sawaki, Y., Arai, Y., Eguchi, M., **Matsuura, R.**, Suzuki. S., & Matsuyama, Y. (2024, July). Building an argument for test score interpretation and use for a fully automated online assessment of L2 spoken interaction. LTRC. Innsbruck, Austria.

-   Suzuki, S., **Matsuura, R.**, Inada, Y., Saeki, M., & Matsuyama, Y. (2023, July). What temporal and dialogic features distinguished between second language oral proficiency levels? The case of oral proficiency interview. AILA. Lyon, France.

-   **Matsuura, R.** & Suzuki, S. (2023, July). Prompt-independent Automated Scoring of L2 Oral Fluency by Capturing Prompt Effects. AIED. Tokyo, Japan.

-   **Matsuura, R.** (2023, June). Developing and validating automatic annotation system of silent pause locations and disfluency words. LTRC. New York City, US.

-   Matsuyama, Y., Suzuki, S., Saeki, M., Takatsu, H., **Matsuura, R.**, & Arai, Y. (2023, June). Towards an explainable automated scoring of spoken interaction with a conversational AI agent. In J. Eunice, & Y. Sawaki. (Convenors), Technology in Diagnostic and Formative Language Assessment: Friend or Foe? LTRC. New York City, US.

-   **Matsuura, R.**, Suzuki, S., Saeki, M., Ogawa, T., & Matsuyama, Y. (2022, November). Refinement of Utterance Fluency Feature Extraction and Automated Scoring of L2 Oral Fluency with Dialogic Features. APSIPA ASC. Chiang-Mai, Thailand.

-   Suzuki, S., **Matsuura, R.**, Saeki, M., & Matsuyama, Y. (2022, August). How is dialogic fluency different from monologic fluency? The case of oral proficiency interview. TBLT. Innsbruck, Austria.

-   Suzuki, S., **Matsuura, R.**, Saeki, M., & Matsuyama, Y. (2022, August). What temporal features distinguish between second language oral proficiency levels? The case of Japanese learners of English. Accepted for presentation at the 31st annual conference of the European Second Language Association (EUROSLA), Fribourg, Switzerland.

-   Suzuki, S., **Matsuura, R.**, Saeki, M., & Matsuyama, Y. (2022, March). Revisiting the assessment potential of read-aloud speech performance: Cognitive validity and predictive validity. LTRC. Tokyo, Japan.

### Non-Refereed Paper and Poster Presentations

-   **Matsuura, R.**, Suzuki, S., Saeki, M., Ogawa, T., & Matsuyama, Y. (2022, March). Automated scoring of L2 fluency based on detection of disfluency words and pause locations. Spring Meeting of ASJ. (松浦瑠希，鈴木駿吾，佐伯真於，小川哲司，松山洋一．(2022, March)．言い淀みとポーズ位置検出に基づく第二言語発話の流暢性自動採点. 日本音響学会研究発表会). Tokyo, Japan. (**Student Presentation Award**).

-   **Matsuura, R.**, Suzuki, S., Saeki, M., Fujie, S., Ogawa, T., & Matsuyama, Y. (2022, June). Automated Scoring of L2 Oral Fluency Using Dialogic Features. Sound Symposium. (松浦瑠希，鈴木駿吾，佐伯真於，藤江真也，小川哲司，松山洋一．(2022, June)．対話特徴を用いた第二言語発話の流暢性自動採点. 音学シンポジウム). Tokyo, Japan. (**Sponsorship Award**).

-   **Matsuura, R.**, & Suzuki, S. (2022, December). Automated Scoring of L2 Oral Fluency Based on Speech Production Model. Conference of Transdisciplinary Federation of Science and Technology (traFST). (松浦瑠希，鈴木駿吾．(2022, December)．発話産出モデルに基づく第二言語発話の流暢性自動採点．横幹連合コンファレンス). Tokyo, Japan.

-   **Matsuura, R.** (2023, October). Automated Scoring of L2 Oral Fluency in Dialogue: Refining of Fluency Feature Extraction & Incorporating Dialogic Features. International Workshop of Speech assessment and native and non-native linguistic variation: trends and methods.